backend:
  name: github
  repo: staketechnologies/HP-2020

media_folder: content/news
publish_mode: editorial_workflow


collections:
  - name: news
    label: News
    folder: /content/news
    identifier_field: name
    slug: "{{year}}-{{month}}-{{day}}"
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }